# Generated by Django 4.0.6 on 2022-07-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('year', models.SmallIntegerField()),
                ('pages', models.IntegerField()),
                ('slug', models.SlugField(null=True)),
            ],
        ),
    ]
